version: "3.8"

services:
  kgpt:
    image: knowledge-gpt
    container_name: knowledge-gpt
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8501:8501
    networks:
      default:
